// Shared helpers for the demo scripts (deploy, seed, lookalike, rehearsal, public demo org). TESTNET ONLY.
import { chmodSync, existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { config as loadDotenv, parse as parseDotenv } from 'dotenv'
import { createClient, http, publicActions, walletActions, type Address, type Hex } from 'viem'
import { Abis, Account } from 'viem/tempo'
import { getNetwork, publicClientFor } from '@bound/core'

export const SERVER_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..')
/** Git-ignored. Holds throwaway testnet keys; never commit it. */
export const SERVER_ENV = resolve(SERVER_DIR, '.env')
/** Git-ignored (apps/web/.gitignore: .env*). */
export const WEB_ENV = resolve(SERVER_DIR, '../web/.env.local')
export const TESTNET_CHAIN_ID = 42431

// Shell variables win over the file (dotenv never overrides), so TEMPO_NETWORK=mainnet in the shell is refused below.
loadDotenv({ path: SERVER_ENV })

export function die(msg: string): never {
  console.error(`\n✗ ${msg}\n`)
  process.exit(1)
}

/**
 * Refuses to run unless the network is explicitly Tempo testnet: TEMPO_NETWORK=testnet (shell or
 * apps/server/.env) or `--network testnet`. Any other value, or a conflict between the two, exits.
 */
export function requireTestnet() {
  const i = process.argv.indexOf('--network')
  const flag = i >= 0 ? process.argv[i + 1] : undefined
  const env = process.env.TEMPO_NETWORK
  if (flag !== undefined && flag !== 'testnet') die(`--network ${flag}: these scripts only run on Tempo testnet (Moderato).`)
  if (flag === undefined && env !== 'testnet') die(`TEMPO_NETWORK is "${env ?? ''}": set TEMPO_NETWORK=testnet or pass --network testnet. These scripts never touch mainnet.`)
  if (env !== undefined && env !== '' && env !== 'testnet') die(`TEMPO_NETWORK=${env} conflicts with --network testnet.`)
  process.env.TEMPO_NETWORK = 'testnet'
  const net = getNetwork('testnet')
  if (net.chain.id !== TESTNET_CHAIN_ID) die(`unexpected testnet chain id ${net.chain.id}`)
  return { name: 'testnet' as const, net, pub: publicClientFor('testnet') }
}

/** Call before sending anything: the RPC must answer with Moderato's chain id. */
export async function assertTestnetChain(pub: { getChainId: () => Promise<number> }) {
  const id = await pub.getChainId()
  if (id !== TESTNET_CHAIN_ID) die(`RPC reports chain id ${id}, expected ${TESTNET_CHAIN_ID} (Tempo Moderato). Nothing was sent.`)
}

/** Required env value (hex keys are checked for shape). */
export function need(name: string): string {
  const v = process.env[name]
  if (!v) die(`${name} is not set in apps/server/.env (run the earlier setup steps first).`)
  return v
}
export const needKey = (name: string) => {
  const v = need(name)
  if (!/^0x[0-9a-fA-F]{64}$/.test(v)) die(`${name} must be a 32-byte hex private key`)
  return v as `0x${string}`
}

/** Upserts KEY=value lines in a dotenv file (created 0600 if missing) and mirrors them into process.env. */
export function setEnv(file: string, updates: Record<string, string>, header?: string) {
  const lines = existsSync(file) ? readFileSync(file, 'utf8').split('\n') : header ? [header] : []
  for (const [k, v] of Object.entries(updates)) {
    const idx = lines.findIndex((l) => l.startsWith(`${k}=`))
    if (idx >= 0) lines[idx] = `${k}=${v}`
    else lines.splice(lines.length && lines[lines.length - 1] === '' ? lines.length - 1 : lines.length, 0, `${k}=${v}`)
    process.env[k] = v
  }
  writeFileSync(file, lines.join('\n').replace(/\n*$/, '\n'), { mode: 0o600 })
  chmodSync(file, 0o600)
}

/**
 * apps/web/.env.local for local dev: public values only (addresses, names), rebuilt from apps/server/.env.
 * Unknown values are left empty until the step that produces them has run.
 */
export function writeWebEnv() {
  // re-read the file: another script may have updated it since this process started
  const e = { ...process.env, ...(existsSync(SERVER_ENV) ? parseDotenv(readFileSync(SERVER_ENV)) : {}) }
  setEnv(WEB_ENV, {
    NEXT_PUBLIC_API_URL: `http://localhost:${e.PORT || 8787}`,
    NEXT_PUBLIC_TEMPO_NETWORK: 'testnet',
    NEXT_PUBLIC_LAB_PAYEE_NAME: e.DEMO_PAYEE_NAME ?? '',
    NEXT_PUBLIC_LAB_PAYEE_WALLET: e.DEMO_PAYEE_ADDRESS ?? '',
    NEXT_PUBLIC_LAB_PAYEE_DOMAIN: e.DEMO_PAYEE_DOMAIN_ATTESTED ?? '',
    NEXT_PUBLIC_LAB_LOOKALIKE: e.LAB_LOOKALIKE_ADDRESS ?? '',
    NEXT_PUBLIC_LAB_UNREGISTERED: e.LAB_UNREGISTERED_ADDRESS ?? '',
  }, '# Generated by apps/server/scripts (testnet demo). Public values only. Git-ignored.')
}

export const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms))

type Pub = ReturnType<typeof publicClientFor>
export const tokenBalance = (pub: Pub, who: `0x${string}`) =>
  pub.readContract({ address: getNetwork('testnet').token, abi: Abis.tip20, functionName: 'balanceOf', args: [who] }) as Promise<bigint>

/**
 * Tops up an address from the Moderato faucet when its pathUSD balance is below `min` (base units).
 * Tries the node's tempo_fundAddress RPC, then the public faucet API; the RPC can time out even though
 * the funds land, so the balance is polled either way.
 */
export async function ensureFunded(pub: Pub, who: `0x${string}`, label: string, min = 1_000_000n) {
  await assertTestnetChain(pub)
  const before = await tokenBalance(pub, who)
  if (before >= min) return before
  try { await pub.request({ method: 'tempo_fundAddress' as any, params: [who] as any }) } catch (e) {
    console.log(`  tempo_fundAddress(${label}): ${(e as Error).message.split('\n')[0]}; trying the faucet API`)
    try {
      const r = await fetch('https://tempo.xyz/developers/api/faucet', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ address: who }) })
      console.log(`  faucet API(${label}): HTTP ${r.status}`)
    } catch (e2) { console.log(`  faucet API(${label}): ${(e2 as Error).message}`) }
  }
  for (let i = 0; i < 45; i++) {
    const b = await tokenBalance(pub, who).catch(() => 0n)
    if (b > before) { console.log(`  funded ${label} ${who}: ${Number(b) / 1e6} pathUSD`); return b }
    await sleep(2000)
  }
  die(`could not fund ${label} ${who} from the testnet faucet`)
}

// ---- demo orgs through a running server (rehearse --fresh-org, demo:public-org) ----

/** The seeded demo org's limits: 50 USD per day, the most the server's demo signer accepts. */
export const DEMO_LIMIT_USD = '50'
export const DEMO_PERIOD_SECONDS = 86_400

/** JSON calls to a running Bound server; any non-2xx throws with the status and body. */
export function boundApi(base: string) {
  return async (method: string, path: string, body?: unknown, token?: string): Promise<any> => {
    const res = await fetch(`${base}${path}`, {
      method, headers: { 'content-type': 'application/json', ...(token ? { authorization: `Bearer ${token}` } : {}) },
      body: body === undefined ? undefined : JSON.stringify(body),
    })
    const json: any = await res.json().catch(() => ({}))
    if (!res.ok) throw new Error(`${method} ${path} → ${res.status} ${JSON.stringify(json)}`)
    return json
  }
}
export type BoundApi = ReturnType<typeof boundApi>

/** DEMO_ROOT_PRIVATE_KEY as a testnet wallet client (demo only: it stands in for a customer's root wallet). Check it with assertTestnetChain before sending. */
export function demoRootClient(net: ReturnType<typeof getNetwork>, rootKey = needKey('DEMO_ROOT_PRIVATE_KEY')) {
  return createClient({ account: Account.fromSecp256k1(rootKey), chain: net.chain, transport: http(net.rpc) }).extend(publicActions).extend(walletActions)
}
export type DemoRootClient = ReturnType<typeof demoRootClient>

/** Signs a prepared call with the demo root (demo only: in the product the customer's wallet signs). */
export async function signAsRoot(root: DemoRootClient, call: { to: Address; data: Hex }): Promise<Hex> {
  const r: any = await root.sendTransactionSync({ ...call, throwOnReceiptRevert: true } as any)
  return r.transactionHash as Hex
}

/**
 * Creates an org through the server's API with the demo root as its root account and the seeded demo org's
 * limits, then authorizes its agent key: the demo root signs the prepared authorizeCall and the server
 * confirms it. The new key's allowlist holds only the root sentinel, as for every new org. The token is
 * returned for the caller to store; never print it.
 */
export async function createAuthorizedDemoOrg(api: BoundApi, root: DemoRootClient, name: string) {
  await assertTestnetChain(root)
  const created = await api('POST', '/v1/orgs', { name, rootAddress: root.account.address, limitUsd: DEMO_LIMIT_USD, periodSeconds: DEMO_PERIOD_SECONDS })
  const authTx = await signAsRoot(root, created.authorizeCall)
  await api('POST', `/v1/orgs/${created.org.id}/authorized`, { txHash: authTx }, created.token)
  return { orgId: created.org.id as string, token: created.token as string, authTx }
}
