// Shared helpers for the demo scripts (deploy, seed, lookalike, rehearsal). TESTNET ONLY.
import { chmodSync, existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { config as loadDotenv } from 'dotenv'
import { Abis } from 'viem/tempo'
import { getNetwork, publicClientFor } from '@bound/core'

export const SERVER_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..')
/** Git-ignored. Holds throwaway testnet keys; never commit it. */
export const SERVER_ENV = resolve(SERVER_DIR, '.env')
/** Git-ignored (apps/web/.gitignore: .env*). */
export const WEB_ENV = resolve(SERVER_DIR, '../web/.env.local')
export const TESTNET_CHAIN_ID = 42431

// Shell variables win over the file (dotenv never overrides), so TEMPO_NETWORK=mainnet in the shell is refused below.
loadDotenv({ path: SERVER_ENV })

export function die(msg: string): never {
  console.error(`\n✗ ${msg}\n`)
  process.exit(1)
}

/**
 * Refuses to run unless the network is explicitly Tempo testnet: TEMPO_NETWORK=testnet (shell or
 * apps/server/.env) or `--network testnet`. Any other value, or a conflict between the two, exits.
 */
export function requireTestnet() {
  const i = process.argv.indexOf('--network')
  const flag = i >= 0 ? process.argv[i + 1] : undefined
  const env = process.env.TEMPO_NETWORK
  if (flag !== undefined && flag !== 'testnet') die(`--network ${flag}: these scripts only run on Tempo testnet (Moderato).`)
  if (flag === undefined && env !== 'testnet') die(`TEMPO_NETWORK is "${env ?? ''}": set TEMPO_NETWORK=testnet or pass --network testnet. These scripts never touch mainnet.`)
  if (env !== undefined && env !== '' && env !== 'testnet') die(`TEMPO_NETWORK=${env} conflicts with --network testnet.`)
  process.env.TEMPO_NETWORK = 'testnet'
  const net = getNetwork('testnet')
  if (net.chain.id !== TESTNET_CHAIN_ID) die(`unexpected testnet chain id ${net.chain.id}`)
  return { name: 'testnet' as const, net, pub: publicClientFor('testnet') }
}

/** Call before sending anything: the RPC must answer with Moderato's chain id. */
export async function assertTestnetChain(pub: { getChainId: () => Promise<number> }) {
  const id = await pub.getChainId()
  if (id !== TESTNET_CHAIN_ID) die(`RPC reports chain id ${id}, expected ${TESTNET_CHAIN_ID} (Tempo Moderato). Nothing was sent.`)
}

/** Required env value (hex keys are checked for shape). */
export function need(name: string): string {
  const v = process.env[name]
  if (!v) die(`${name} is not set in apps/server/.env (run the earlier setup steps first).`)
  return v
}
export const needKey = (name: string) => {
  const v = need(name)
  if (!/^0x[0-9a-fA-F]{64}$/.test(v)) die(`${name} must be a 32-byte hex private key`)
  return v as `0x${string}`
}

/** Upserts KEY=value lines in a dotenv file (created 0600 if missing) and mirrors them into process.env. */
export function setEnv(file: string, updates: Record<string, string>, header?: string) {
  const lines = existsSync(file) ? readFileSync(file, 'utf8').split('\n') : header ? [header] : []
  for (const [k, v] of Object.entries(updates)) {
    const idx = lines.findIndex((l) => l.startsWith(`${k}=`))
    if (idx >= 0) lines[idx] = `${k}=${v}`
    else lines.splice(lines.length && lines[lines.length - 1] === '' ? lines.length - 1 : lines.length, 0, `${k}=${v}`)
    process.env[k] = v
  }
  writeFileSync(file, lines.join('\n').replace(/\n*$/, '\n'), { mode: 0o600 })
  chmodSync(file, 0o600)
}

/**
 * apps/web/.env.local for local dev: public values only (addresses, names), rebuilt from apps/server/.env.
 * Unknown values are left empty until the step that produces them has run.
 */
export function writeWebEnv() {
  const e = process.env
  setEnv(WEB_ENV, {
    NEXT_PUBLIC_API_URL: `http://localhost:${e.PORT || 8787}`,
    NEXT_PUBLIC_TEMPO_NETWORK: 'testnet',
    NEXT_PUBLIC_LAB_PAYEE_NAME: e.DEMO_PAYEE_NAME ?? '',
    NEXT_PUBLIC_LAB_PAYEE_WALLET: e.DEMO_PAYEE_ADDRESS ?? '',
    NEXT_PUBLIC_LAB_PAYEE_DOMAIN: e.DEMO_PAYEE_DOMAIN_ATTESTED ?? '',
    NEXT_PUBLIC_LAB_LOOKALIKE: e.LAB_LOOKALIKE_ADDRESS ?? '',
    NEXT_PUBLIC_LAB_UNREGISTERED: e.LAB_UNREGISTERED_ADDRESS ?? '',
  }, '# Generated by apps/server/scripts (testnet demo). Public values only. Git-ignored.')
}

export const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms))

type Pub = ReturnType<typeof publicClientFor>
export const tokenBalance = (pub: Pub, who: `0x${string}`) =>
  pub.readContract({ address: getNetwork('testnet').token, abi: Abis.tip20, functionName: 'balanceOf', args: [who] }) as Promise<bigint>

/**
 * Tops up an address from the Moderato faucet when its pathUSD balance is below `min` (base units).
 * Tries the node's tempo_fundAddress RPC, then the public faucet API; the RPC can time out even though
 * the funds land, so the balance is polled either way.
 */
export async function ensureFunded(pub: Pub, who: `0x${string}`, label: string, min = 1_000_000n) {
  await assertTestnetChain(pub)
  const before = await tokenBalance(pub, who)
  if (before >= min) return before
  try { await pub.request({ method: 'tempo_fundAddress' as any, params: [who] as any }) } catch (e) {
    console.log(`  tempo_fundAddress(${label}): ${(e as Error).message.split('\n')[0]}; trying the faucet API`)
    try {
      const r = await fetch('https://tempo.xyz/developers/api/faucet', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ address: who }) })
      console.log(`  faucet API(${label}): HTTP ${r.status}`)
    } catch (e2) { console.log(`  faucet API(${label}): ${(e2 as Error).message}`) }
  }
  for (let i = 0; i < 45; i++) {
    const b = await tokenBalance(pub, who).catch(() => 0n)
    if (b > before) { console.log(`  funded ${label} ${who}: ${Number(b) / 1e6} pathUSD`); return b }
    await sleep(2000)
  }
  die(`could not fund ${label} ${who} from the testnet faucet`)
}
